# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /configuration-image

# Copy the Python scripts into the container
COPY ./ /configuration-image/

# Run main.py when the container launches
CMD ["python", "main.py"]
#terminal code
#docker image build -t configuration-app:1.0
#docker tag configuration-app simal4321/configuration-app:1.0

